In [2]:
import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [4]:
pd.set_option('display.float_format', '{:.1f}'.format)

In [5]:
pd.set_option('display.max_columns', None)

In [6]:
import matplotlib.font_manager as fm

NanumBarunGothic_path = './fonts/NanumBarunGothic.ttf'
fm.fontManager.addfont(NanumBarunGothic_path)

plt.rc('font', family='NanumBarunGothic')

In [7]:
base_path = r'C:\Users\haruka\Desktop\AI수업\mcp-month-2\data'

In [8]:
file_name = '국민연금공단_국민연금 가입 사업장 내역_20260923.csv'

In [49]:
df = pd.read_csv(os.path.join(base_path, file_name), encoding='cp949')

C:\Users\haruka\AppData\Local\Temp\ipykernel_24508\1537392518.py:1: DtypeWarning: Columns (4: 우편번호, 8: 고객행정동주소코드) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(os.path.join(base_path, file_name), encoding='cp949')

In [11]:
df.head(3)

,자료생성년월,사업장명,사업자등록번호,사업장가입상태코드 1 등록 2 탈퇴,우편번호,사업장지번상세주소,사업장도로명상세주소,고객법정동주소코드,고객행정동주소코드,법정동주소광역시도코드,법정동주소광역시시군구코드,법정동주소광역시시군구읍면동코드,사업장형태구분코드 1 법인 2 개인,사업장업종코드,사업장업종코드명,적용일자,재등록일자,탈퇴일자,가입자수,당월고지금액,신규취득자수,상실가입자수
0,2026-08,우성기전(주),126811,1,12816,경기도 광주시 도척면,경기도 광주시 도척면 도척윗로,4161033025,4161033000,41,610,330,1,292201,동력식 수지 공구 제조업,1988-01-01,NaN,NaN,4,938400,0,0
1,2026-08,희성전자(주),106810,1,04410,서울특별시 용산구 한남동,서울특별시 용산구 독서당로14길,1117013100,1117068500,11,170,131,1,701201,비주거용 건물 임대업(점포 자기땅),1988-01-01,NaN,NaN,291,175743480,0,3
2,2026-08,(주)신영인사이트,201853,2,04536,서울특별시 중구 명동2가,서울특별시 중구 명동8길,1114012700,1114055000,11,140,127,1,701201,비주거용 건물 임대업(점포 자기땅),1988-01-01,NaN,2026-07-01,0,0,0,0

In [12]:
df.shape

(591028, 22)

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 591028 entries, 0 to 591027
Data columns (total 22 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   자료생성년월               591028 non-null  str
 1   사업장명                 591028 non-null  str
 2   사업자등록번호              591028 non-null  int64
 3   사업장가입상태코드 1 등록 2 탈퇴  591028 non-null  int64
 4   우편번호                 591028 non-null  object
 5   사업장지번상세주소            591028 non-null  str
 6   사업장도로명상세주소           568529 non-null  str
 7   고객법정동주소코드            591028 non-null  int64
 8   고객행정동주소코드            591028 non-null  object
 9   법정동주소광역시도코드          591028 non-null  int64
 10  법정동주소광역시시군구코드        591028 non-null  int64
 11  법정동주소광역시시군구읍면동코드     591028 non-null  int64
 12  사업장형태구분코드 1 법인 2 개인  591028 non-null  int64
 13  사업장업종코드              591028 non-null  int64
 14  사업장업종코드명             590319 non-null  str
 15  적용일자                 591023 non-null  str
 16  재등록일자                20282 non-null   str
 17  탈퇴일자                 38163 non-null   str
 18  가입자수                 591028 non-null  int64
 19  당월고지금액               591028 non-null  int64
 20  신규취득자수               591028 non-null  int64
 21  상실가입자수               591028 non-null  int64
dtypes: int64(12), object(2), str(8)
memory usage: 99.2+ MB

In [50]:
df.columns = [
    '자료생성년월',
    '사업장명',
    '사업자등록번호',
    '가입상태',
    '우편번호',
    '사업장지번상세주소',
    '주소',
    '고객법정동주소코드',
    '고객행정동주소코드',
    '시도코드',
    '시군구코드',
    '읍면동코드',
    '사업장형태구분코드 1 법인 2 개인',
    '업종코드',
    '업종코드명',
    '적용일자',
    '재등록일자',
    '탈퇴일자',
    '가입자수',
    '금액',
    '신규',
    '상실'
]

In [51]:
df.columns

Index(['자료생성년월', '사업장명', '사업자등록번호', '가입상태', '우편번호', '사업장지번상세주소', '주소',
       '고객법정동주소코드', '고객행정동주소코드', '시도코드', '시군구코드', '읍면동코드',
       '사업장형태구분코드 1 법인 2 개인', '업종코드', '업종코드명', '적용일자', '재등록일자', '탈퇴일자', '가입자수',
       '금액', '신규', '상실'],
      dtype='str')

In [52]:
df.drop([
  '자료생성년월',
  '우편번호',
  '사업장지번상세주소',
  '고객법정동주소코드',
  '고객행정동주소코드',
  '사업장형태구분코드 1 법인 2 개인',
  '적용일자',
  '재등록일자'
], inplace=True, axis=1)

In [24]:
df.shape

(591028, 14)

In [53]:
df.dropna(subset=['사업장명', '사업자등록번호', '시도코드'], inplace=True)

In [26]:
df.shape

(591028, 14)

In [27]:
df['사업장명'].str

In [28]:
df['사업장명'].str.contains(r'\(주\)')

0          True
1          True
2          True
3          True
4          True
          ...
591023    False
591024    False
591025     True
591026    False
591027     True
Name: 사업장명, Length: 591028, dtype: bool

In [30]:
ju_loc = df.loc[df['사업장명'].str.contains(r'\(주\)')]

In [37]:
ju_loc.head(3)

,사업장명,사업자등록번호,가입상태,주소,시도코드,시군구코드,읍면동코드,업종코드,업종코드명,탈퇴일자,가입자수,금액,신규,상실
0,우성기전(주),126811,1,경기도 광주시 도척면 도척윗로,41,610,330,292201,동력식 수지 공구 제조업,NaN,4,938400,0,0
1,희성전자(주),106810,1,서울특별시 용산구 독서당로14길,11,170,131,701201,비주거용 건물 임대업(점포 자기땅),NaN,291,175743480,0,3
2,(주)신영인사이트,201853,2,서울특별시 중구 명동8길,11,140,127,701201,비주거용 건물 임대업(점포 자기땅),2026-07-01,0,0,0,0

In [32]:
ju_loc['사업장명']

0                                                   우성기전(주)
1                                                   희성전자(주)
2                                                 (주)신영인사이트
3                                                  디에스디엘(주)
4                                                    (주)헤럴드
                                ...
591013                                      (주)한국오존텍 건설일용관리
591015    (주)엑사이엔씨/일용/평택 전자 P5 복합동 신축공사 중 [Ph1]평택 전자 P5 ...
591019              대아이앤씨(주)-(일용)C4 안전밸브 정기검사 및 열교환기 크리닝 계약
591025            (주)중선아이티씨/일용/26년 기흥 화성 노후FAN 교체 공사 중 전기공사
591027               청원산기(주)/일용/광양 원료공장 통행로 보도판 및 지지대 교체 2차
Name: 사업장명, Length: 164003, dtype: str

In [35]:
pattern1 = r'(\([^)]+\))'
re.sub(pattern1, '', '우성기전(주)')

'우성기전'

In [38]:
bracket_loc = df.loc[df['사업장명'].str.contains(r'\[')]

In [39]:
bracket_loc.head(3)

,사업장명,사업자등록번호,가입상태,주소,시도코드,시군구코드,읍면동코드,업종코드,업종코드명,탈퇴일자,가입자수,금액,신규,상실
104684,에스티테크[주],606817,1,부산광역시 사하구 감천항로419번길,26,380,107,291502,기타 물품 취급장비 제조업,NaN,10,4271480,0,1
149341,게스트하우스 [특별자활],206826,1,서울특별시 성동구 가람길,11,200,118,999999,BIZ_NO미존재사업장,NaN,10,1251260,1,0
149954,[주)한빛관리 은행대우 3차1단지/ 생활지원센타],212813,1,경기도 시흥시 은행로,41,390,106,702003,비주거용 부동산 관리업,NaN,5,1633100,0,1

In [36]:
pattern2 = r'(\[[^)]+\])'
re.sub(pattern2, '', '에스티테크[주]')

'에스티테크'

In [40]:
special_loc = df.loc[df['사업장명'].str.contains(r'\/')]

In [41]:
special_loc.head(3)

,사업장명,사업자등록번호,가입상태,주소,시도코드,시군구코드,읍면동코드,업종코드,업종코드명,탈퇴일자,가입자수,금액,신규,상실
916,(주)동양/건재부문,101853,1,서울특별시 마포구 마포대로,11,440,102,269401,시멘트 제조업,NaN,299,166486480,0,4
2093,재우교통/주,205812,1,서울특별시 마포구 가양대로,11,440,127,602201,택시 운송업,NaN,4,1190800,1,0
4545,(주)한영파트너스FH/월드컵현대아파트,138810,1,서울특별시 서대문구 수색로,11,410,119,702003,비주거용 부동산 관리업,NaN,3,1103300,0,0

In [42]:
pattern3 = '[^A-Za-z0-9가-힣]'
result = re.sub(pattern3, ' ', '*&&^%의료법인%해정')

In [43]:
result

'     의료법인 해정'

In [44]:
result = re.sub(' +', ' ', result)

In [45]:
result

' 의료법인 해정'

In [55]:
def preprocessing(x):
  x = re.sub(pattern1, '', x)
  x = re.sub(pattern2, '', x)
  x = re.sub(pattern3, ' ', x)
  x = re.sub(' +', ' ', x)
  return x.strip()

In [56]:
df['사업장명'] = df['사업장명'].apply(preprocessing)

In [48]:
df['사업장명']

0                                             우성기전
1                                             희성전자
2                                           신영인사이트
3                                            디에스디엘
4                                              헤럴드
                            ...
591023    주식회사 트레이스 설천중고 외 1교관사 화장실 수선 및 기타 기계설비공사
591024    주식회사 예숨 일용 2026년 천보사 자연휴양림 숲속의 집 A동 정비사업
591025      중선아이티씨 일용 26년 기흥 화성 노후FAN 교체 공사 중 전기공사
591026                      주 부현전기 창원HVDC공장 중 접지공사
591027         청원산기 일용 광양 원료공장 통행로 보도판 및 지지대 교체 2차
Name: 사업장명, Length: 591028, dtype: str

In [57]:
df.loc[[0, 112863, 718]]

,사업장명,사업자등록번호,가입상태,주소,시도코드,시군구코드,읍면동코드,업종코드,업종코드명,탈퇴일자,가입자수,금액,신규,상실
0,우성기전,126811,1,경기도 광주시 도척면 도척윗로,41,610,330,292201,동력식 수지 공구 제조업,NaN,4,938400,0,0
112863,제영,620813,1,울산광역시 울주군 두서면 전읍농공길,31,710,370,343000,그 외 자동차용 신품 부품 제조업,NaN,11,4212300,0,0
718,삼포산업,119810,1,경기도 하남시 미사강변동로84번길,41,450,109,272300,알루미늄 압연 압출 및 연신제품 제조업,NaN,9,4730740,0,0

In [58]:
year = 2025

In [60]:
join_mask = df['가입상태'] == 1

In [61]:
df = df.loc[join_mask].drop(['가입상태', '탈퇴일자'], axis=1).reset_index(drop=True)

In [62]:
df.head()

,사업장명,사업자등록번호,주소,시도코드,시군구코드,읍면동코드,업종코드,업종코드명,가입자수,금액,신규,상실
0,우성기전,126811,경기도 광주시 도척면 도척윗로,41,610,330,292201,동력식 수지 공구 제조업,4,938400,0,0
1,희성전자,106810,서울특별시 용산구 독서당로14길,11,170,131,701201,비주거용 건물 임대업(점포 자기땅),291,175743480,0,3
2,디에스디엘,104811,서울특별시 중구 세종대로,11,140,117,701201,비주거용 건물 임대업(점포 자기땅),15,5884660,0,1
3,헤럴드,104810,서울특별시 용산구 후암로4길,11,170,101,221200,잡지 및 정기 간행물 발행업,328,155596360,0,3
4,천일해운,105816,서울특별시 용산구 대사관로12길,11,170,131,519113,상품 종합 도매업,8,3043360,1,1

In [63]:
df['인당금액'] = df['금액'] / df['가입자수']

In [64]:
df['월급여추정'] = df['인당금액'] / 9 * 100

In [65]:
df['연간급여추정'] = df['월급여추정'] * 12

In [66]:
df

,사업장명,사업자등록번호,주소,시도코드,시군구코드,읍면동코드,업종코드,업종코드명,가입자수,금액,신규,상실,인당금액,월급여추정,연간급여추정
0,우성기전,126811,경기도 광주시 도척면 도척윗로,41,610,330,292201,동력식 수지 공구 제조업,4,938400,0,0,234600.0,2606666.7,31280000.0
1,희성전자,106810,서울특별시 용산구 독서당로14길,11,170,131,701201,비주거용 건물 임대업(점포 자기땅),291,175743480,0,3,603929.5,6710327.6,80523931.3
2,디에스디엘,104811,서울특별시 중구 세종대로,11,140,117,701201,비주거용 건물 임대업(점포 자기땅),15,5884660,0,1,392310.7,4359007.4,52308088.9
3,헤럴드,104810,서울특별시 용산구 후암로4길,11,170,101,221200,잡지 및 정기 간행물 발행업,328,155596360,0,3,474379.1,5270879.4,63250552.8
4,천일해운,105816,서울특별시 용산구 대사관로12길,11,170,131,519113,상품 종합 도매업,8,3043360,1,1,380420.0,4226888.9,50722666.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552860,주식회사 트레이스 설천중고 외 1교관사 화장실 수선 및 기타 기계설비공사,246860,전북특별자치도 무주군 설천면 하평지길,52,730,320,452124,건물용 기계ㆍ장비 설치 공사업,4,1433540,4,0,358385.0,3982055.6,47784666.7
552861,주식회사 예숨 일용 2026년 천보사 자연휴양림 숲속의 집 A동 정비사업,687880,경기도 포천시 원동교길,41,650,106,514393,그 외 기타 건축자재 도매업,4,767380,4,4,191845.0,2131611.1,25579333.3
552862,중선아이티씨 일용 26년 기흥 화성 노후FAN 교체 공사 중 전기공사,220810,경기도 용인시 기흥구 삼성로,41,463,109,452104,배관 및 냉ㆍ난방 공사업,8,3590960,8,0,448870.0,4987444.4,59849333.3
552863,주 부현전기 창원HVDC공장 중 접지공사,118812,경상남도 창원시 성산구 공단로,48,123,129,452126,내부 전기배선 공사업,3,1596000,3,0,532000.0,5911111.1,70933333.3
552864,청원산기 일용 광양 원료공장 통행로 보도판 및 지지대 교체 2차,417812,전남광주통합특별시 광양시 제철로,12,190,110,451300,산업 생산시설 종합 건설업,4,1232720,4,0,308180.0,3424222.2,41090666.7

In [68]:
cond = df['가입자수'] > 1000
df.sort_values(['연간급여추정', '가입자수'], ascending=False)\
    .loc[cond, ['사업장명', '가입자수', '월급여추정', '연간급여추정']]

                   사업장명   가입자수     월급여추정     연간급여추정
6072            기아 영업본부   1829 6956000.0 83472000.0
6166            기아 정비본부   1074 6955849.6 83470194.9
205455   부산항만산업협회 화물고정업   1106 6940998.2 83291978.3
136281             현대위아   2756 6928196.4 83138357.0
15425          한국지엠주식회사   7459 6920120.8 83041449.7
...                 ...    ...       ...        ...
37757        한국맥도날드유한회사  11833 1307786.0 15693431.8
337161  씨제이올리브영주식회사 비정규   9518 1306223.2 15674678.7
5285              단국대학교   1144 1234372.8 14812473.2
48739     주식회사 케이에프씨코리아   2068 1210024.5 14520294.0
165827      한국문화예술교육진흥원   3165  967600.8 11611209.3

[758 rows x 4 columns]

In [69]:
def find_company(company_name, contains):
  if contains:
    return df.loc[
      df['사업장명'].str.contains(company_name),
      ['사업장명', '월급여추정', '연간급여추정', '업종코드', '가입자수']
    ].sort_values('가입자수', ascending=False)
  else:
    return df.loc[
      df['사업장명'] == company_name,
      ['사업장명', '월급여추정', '연간급여추정', '업종코드', '가입자수']
    ].sort_values('가입자수', ascending=False)

In [70]:
find_company('에스케이텔레콤', False)

         사업장명     월급여추정     연간급여추정    업종코드  가입자수
3212  에스케이텔레콤 6632273.3 79587279.1  642001  5012

In [71]:
find_company('에스케이텔레콤', True)

,사업장명,월급여추정,연간급여추정,업종코드,가입자수
3212,에스케이텔레콤,6632273.3,79587279.1,642001,5012
339013,에스케이텔레콤씨에스티원,3766426.7,45197120.9,924101,113
486478,에스케이텔레콤 주 상용 오픈 이노베이션 지향 Lv 4 4 자율주행 리빙랩 구축사업,6956000.0,83472000.0,642001,7
415829,에스케이텔레콤 상용 경북 사업장 형태선LTE R,6701888.9,80422666.7,642001,4
126057,주식회사 에스케이텔레콤봉화대리점,2567407.4,30808888.9,523323,3
225466,에스케이텔레콤 철원동송대리점,4312963.0,51755555.6,515060,3

In [76]:
def compare_company(company_name):
  company = find_company(company_name, True)
  code = company['업종코드'].iloc[0]
  df1 = df.loc[df['업종코드'] == code, ['월급여추정', '연간급여추정']]\
          .agg(['mean', 'count', 'min', 'max'])
  df1.columns = ['업종_월급여추정', '업종_연간급여추정']
  df1 = df1.T
  df1.columns = ['평균', '개수', '최소', '최대']
  df1.loc['업종_월급여추정', company_name] = company['월급여추정'].values[0]
  df1.loc['업종_연간급여추정', company_name] = company['연간급여추정'].values[0]
  return df1

In [77]:
compare_company('삼성전자')

                  평균    개수        최소         최대       삼성전자
업종_월급여추정   3714648.4 411.0  432666.7  6956000.0  6884033.2
업종_연간급여추정 44575781.1 411.0 5192000.0 83472000.0 82608397.8