In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [4]:
base_path = r'c:\Users\haruka\Desktop\AI수업\mcp-month-2\data'

In [5]:
fish_df = pd.read_csv(os.path.join(base_path, 'fish.csv'))

In [6]:
fish_df.Species.unique()

<StringArray>
['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt']
Length: 7, dtype: str

In [7]:
fish_df.columns

Index(['Species', 'Weight', 'Length', 'Diagonal', 'Height', 'Width'], dtype='str')

In [8]:
fish_input = fish_df[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].to_numpy()

In [9]:
fish_input[:5]

array([[242.    ,  25.4   ,  30.    ,  11.52  ,   4.02  ],
       [290.    ,  26.3   ,  31.2   ,  12.48  ,   4.3056],
       [340.    ,  26.5   ,  31.1   ,  12.3778,   4.6961],
       [363.    ,  29.    ,  33.5   ,  12.73  ,   4.4555],
       [430.    ,  29.    ,  34.    ,  12.444 ,   5.134 ]])

In [10]:
fish_target = fish_df['Species'].to_numpy()

In [11]:
fish_target

array(['Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach',
       'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Roach', 'Whitefish',
       'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish', 'Whitefish',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki',
       'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Parkki', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Perch',
       'Perch', 'Perch', 'Perch', 'Perch', 'Perch', 'Pike', 'Pike',
       'Pike', 'Pike', 'Pike', 'Pike', 'Pike', 'Pike', 'Pike', 'Pike',
       'Pike', 'Pike', 'Pike', 'Pike', 'Pike', 'Pike', 'Pike', 'Smelt',
       'Smelt', 'Smelt', 'Smelt', 'Smelt', 'Smelt', 'Smelt', 'Smelt',
       'Smelt', 'Smelt', 'Smelt', 'Smelt', 'Smelt', 'Smelt'], dtype=object)

In [12]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target =\
train_test_split(fish_input, fish_target, random_state=42)

In [13]:
print(train_input.shape, test_input.shape)

(119, 5) (40, 5)

In [14]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

In [15]:
train_input[:5]

array([[720.    ,  35.    ,  40.6   ,  16.3618,   6.09  ],
       [500.    ,  45.    ,  48.    ,   6.96  ,   4.896 ],
       [  7.5   ,  10.5   ,  11.6   ,   1.972 ,   1.16  ],
       [110.    ,  22.    ,  23.5   ,   5.5225,   3.995 ],
       [140.    ,  20.7   ,  23.2   ,   8.5376,   3.2944]])

In [16]:
train_scaled[:5]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [ 0.30041219,  1.54653445,  1.45316551, -0.46981663,  0.27291745],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [-0.79734143, -0.60880176, -0.67486907, -0.82480589, -0.27631471],
       [-0.71289885, -0.73062511, -0.70092664, -0.0802298 , -0.7033869 ]])

In [18]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target);

In [19]:
print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.8907563025210085
0.85

In [20]:
pd.unique(fish_df['Species'])

<StringArray>
['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt']
Length: 7, dtype: str

In [21]:
kn.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [22]:
kn.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Perch', 'Perch'], dtype=object)

In [23]:
test_target[:5]

array(['Perch', 'Smelt', 'Pike', 'Whitefish', 'Perch'], dtype=object)

In [25]:
proba = kn.predict_proba(test_scaled[:5])

print(kn.classes_)

print(np.round(proba, decimals=4))

['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
[[0.     0.     1.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     1.     0.     0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]]

In [26]:
distances, indexes = kn.kneighbors(test_scaled[3:4])

print(train_target[indexes])

[['Roach' 'Perch' 'Perch']]

In [27]:
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')

In [28]:
bream_smelt_indexes

array([ True, False,  True, False, False, False, False,  True, False,
       False, False,  True, False, False, False,  True,  True, False,
       False,  True, False,  True, False, False, False,  True, False,
       False,  True, False, False, False, False,  True, False, False,
        True,  True, False, False, False, False, False,  True, False,
       False, False, False, False,  True, False,  True, False, False,
        True, False, False, False,  True, False, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False, False, False, False,  True, False,  True, False,
       False,  True,  True, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False,  True, False,
        True, False, False,  True,  True, False, False, False, False,
       False, False, False, False,  True,  True, False, False,  True,
       False, False])

In [29]:
np.sum(bream_smelt_indexes)

np.int64(33)

In [30]:
train_bream_smelt = train_scaled[bream_smelt_indexes] # (33, 5)
target_bream_smelt = train_target[bream_smelt_indexes] # (33,)

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt);

In [33]:
print("예측: ", lr.predict(train_bream_smelt[:5]))

예측:  ['Bream' 'Smelt' 'Bream' 'Bream' 'Bream']

In [34]:
print("실제: ", target_bream_smelt[:5])

실제:  ['Bream' 'Smelt' 'Bream' 'Bream' 'Bream']

In [35]:
print(lr.classes_)
print(lr.predict_proba(train_bream_smelt[:5]))

['Bream' 'Smelt']
[[0.99760007 0.00239993]
 [0.02737325 0.97262675]
 [0.99486386 0.00513614]
 [0.98585047 0.01414953]
 [0.99767419 0.00232581]]

In [36]:
print(lr.coef_, lr.intercept_)

[[-0.40451732 -0.57582787 -0.66248158 -1.01329614 -0.73123131]] [-2.16172774]

In [37]:
decisions = lr.decision_function(train_bream_smelt[:5])
decisions

array([-6.02991358,  3.57043428, -5.26630496, -4.24382314, -6.06135688])

In [38]:
from scipy.special import expit
print(expit(decisions))

[0.00239993 0.97262675 0.00513614 0.01414953 0.00232581]

In [39]:
lr = LogisticRegression(C=20, max_iter=1000) # 규제는 완화, 반복횟수를 늘림
lr.fit(train_scaled, train_target);

In [40]:
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.9327731092436975
0.925

In [41]:
print("예측:", lr.predict(test_scaled[:5]))

예측: ['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']

In [42]:
print('실제:', test_target[:5])

실제: ['Perch' 'Smelt' 'Pike' 'Whitefish' 'Perch']

In [49]:
proba = lr.predict_proba(test_scaled[:5])
proba_df = pd.DataFrame(data=np.round(proba, decimals=3), columns=lr.classes_)

In [50]:
proba_df

   Bream  Parkki  Perch   Pike  Roach  Smelt  Whitefish
0  0.000   0.014  0.842  0.000  0.135  0.007      0.003
1  0.000   0.003  0.044  0.000  0.007  0.946      0.000
2  0.000   0.000  0.034  0.934  0.015  0.016      0.000
3  0.011   0.034  0.305  0.006  0.567  0.000      0.076
4  0.000   0.000  0.904  0.002  0.089  0.002      0.001

In [51]:
lr.coef_

array([[-1.50605455, -1.03747913,  2.60919713,  7.69422739, -1.18603342],
       [ 0.19200047, -1.99988812, -3.79617725,  6.50312639, -2.00022754],
       [ 3.55793539,  6.36988929, -8.52233732, -5.75397233,  3.79233438],
       [-0.11453308,  3.61060121,  3.94464503, -3.62243904, -1.7598168 ],
       [-1.40843717, -6.09242191,  5.28629633, -0.86696569,  1.84518455],
       [-1.33419952,  1.48153392,  1.38217547, -5.6602348 , -4.39228963],
       [ 0.61328846, -2.33223527, -0.90379939,  1.70625807,  3.70084846]])

In [52]:
decision = lr.decision_function(test_scaled[:5])
df = pd.DataFrame(data=np.round(decision, decimals=2), columns=lr.classes_)

In [53]:
df

   Bream  Parkki  Perch  Pike  Roach  Smelt  Whitefish
0  -6.51    1.04   5.17 -2.76   3.34   0.35      -0.63
1 -10.88    1.94   4.78 -2.42   2.99   7.84      -4.25
2  -4.34   -6.24   3.17  6.48   2.36   2.43      -3.87
3  -0.69    0.45   2.64 -1.21   3.26  -5.70       1.26
4  -6.40   -1.99   5.82 -0.13   3.50  -0.09      -0.70

In [54]:
from scipy.special import softmax

proba = softmax(decision, axis=1)
print(np.round(proba, decimals=3))

[[0.    0.014 0.842 0.    0.135 0.007 0.003]
 [0.    0.003 0.044 0.    0.007 0.946 0.   ]
 [0.    0.    0.034 0.934 0.015 0.016 0.   ]
 [0.011 0.034 0.305 0.006 0.567 0.    0.076]
 [0.    0.    0.904 0.002 0.089 0.002 0.001]]